### 1.	Write a Python Program to Add Two Matrices?

In [21]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(X)):
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]
        
for r in result:
    print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


### 2.	Write a Python Program to Multiply Two Matrices?

In [8]:
import numpy as np

In [23]:
X = [[12,7,3],
    [4,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]


result = np.dot(X,Y)
        
for r in result:
    print(r)

[114 160  60]
[74 97 73]
[119 157 112]


### 3.	Write a Python Program to Transpose a Matrix?

In [10]:
X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

for i in range(len(X)):
    for j in range(len(X[0])):
        result[j][i] = X[i][j]
        
for r in result:
    print(r)

[12, 4, 3]
[7, 5, 8]


### 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [11]:
my_list = ['z','d','p','u','g']
my_list.sort()
print(my_list)

['d', 'g', 'p', 'u', 'z']


### 5.	Write a Python Program to Remove Punctuation From a String?

In [18]:
import re

a = "Gfg, is best : for ! Geeks ;"

print("The original string is: ", a)

res = re.sub(r'[^\w\s]', '', a)

print("After removing punctuation: ", res)



The original string is:  Gfg, is best : for ! Geeks ;
After removing punctuation:  Gfg is best  for  Geeks 


### THE END